import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { computeStaleDocs, staleDocsSection, writeStaleDocs } from './stale-docs.mjs'

const CHANGELOG = 'docs/design-system/changelog.md'
const MARKER = '<!-- entries -->'

function diffMaps(prev = {}, next = {}) {
  const added = []
  const changed = []
  const removed = []
  for (const [key, val] of Object.entries(next)) {
    if (!prev[key]) added.push(val.name)
    else if (prev[key].updatedAt !== val.updatedAt) changed.push(val.name)
  }
  for (const [key, val] of Object.entries(prev)) {
    if (!next[key]) removed.push(val.name)
  }
  return { added: added.sort(), changed: changed.sort(), removed: removed.sort() }
}

// Keep only standalone components (no set). Set-member variants are reported via the
// "Component sets" section instead of as noisy "Property 1=…" variant names.
function standalone(map = {}) {
  return Object.fromEntries(Object.entries(map).filter(([, v]) => !v.set))
}

// Compare two snapshots (from snapshot.mjs). Returns a structured diff.
export function diffSnapshots(prev, next) {
  if (!prev) return { firstRun: true }
  return {
    firstRun: false,
    publishDetected: prev.library?.version !== next.library?.version,
    components: diffMaps(standalone(prev.library?.components), standalone(next.library?.components)),
    componentSets: diffMaps(prev.library?.componentSets, next.library?.componentSets),
    styles: diffMaps(prev.library?.styles, next.library?.styles),
    designVersionChanged: prev.design?.version !== next.design?.version,
  }
}

export function hasChanges(diff) {
  if (!diff || diff.firstRun) return false
  return [diff.components, diff.componentSets, diff.styles].some(
    (b) => b.added.length || b.changed.length || b.removed.length,
  )
}

function section(title, list) {
  if (!list.length) return ''
  return `\n**${title}** (${list.length})\n${list.map((n) => `- ${n}`).join('\n')}\n`
}

// Prepend a dated entry to the changelog when the library changed. No-op otherwise.
export function writeChangelog(diff, snapshot) {
  if (!hasChanges(diff)) return false
  mkdirSync('docs/design-system', { recursive: true })

  if (!existsSync(CHANGELOG)) {
    writeFileSync(
      CHANGELOG,
      `# Design System Changelog\n\nAuto-generated by \`npm run sync\` when the Transportly UI Kit library changes.\n\n${MARKER}\n`,
    )
  }

  const date = snapshot.takenAt.slice(0, 10)
  const version = snapshot.library?.version || 'unknown'
  let entry = `\n## ${date} — Library v${version}\n`
  for (const [label, bucket] of [
    ['Components', diff.components],
    ['Component sets', diff.componentSets],
    ['Styles', diff.styles],
  ]) {
    entry += section(`${label} added`, bucket.added)
    entry += section(`${label} changed`, bucket.changed)
    entry += section(`${label} removed`, bucket.removed)
  }

  // Flag the documentation that depends on the changed components (markdown doc + Figma showcase).
  const stale = computeStaleDocs(diff)
  entry += staleDocsSection(stale)
  writeStaleDocs(stale, snapshot)

  const current = readFileSync(CHANGELOG, 'utf8')
  const out = current.includes(MARKER)
    ? current.replace(MARKER, `${MARKER}\n${entry}`)
    : `${current}\n${entry}`
  writeFileSync(CHANGELOG, out)
  return true
}
